### PR TITLE
Watchdog and display cleanup

### LINKED ISSUE #16: Watchdog for AVR
When the AVR crashes for any reason the soldering iron has to be disconnected from power. When the pin to power the iron is high, when the AVR crashes the tip will not be disconnected from power until it reboots. This poses a safety issue and should be addressed.

### PR DESCRIPTION
**Pull request by oni303**
Closes #16 by activating the watchdog

After the AVR was reseted by the watchdog the tip is not heated again
until the device was power cycled. Until then an error is displayed.

### CODE REVIEW

File: Firmware/includes/display.c [hunk 1]
```diff
@@ -5,52 +5,11 @@
 #include "timing.h"
 
 
-#define DISPLAY_REFRESH_INTERVAL 60 // 0.5ms 
+#define DISPLAY_REFRESH_INTERVAL 1 // 0.5ms
```
Comment (kartenkarsten) [inline Firmware/includes/display.c]: is it right that the comment wasn't changed?

**Comment by yschroeder** [comment]
I really like how the display cycles its text when in watchdog error mode.

Good work! :+1:
